### ISSUE TITLE
TravisCI support

### ISSUE THREAD

**Issue by vk496** [nfc-tools/mfoc-hardnested#4]
@doegox could you please enable TravisCI for this repo? I don't have enough rights to do it.

Br,
Valentín :)

**Comment by LudovicRousseau** [comment]
What is the procedure to enable TravisCI?

**Comment by neomilium** [comment]
[Travis-CI has decided to adjust its business model in a way that Open Source projects buy CI minutes each month](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) so it may be interesting to use directly _GitHub Actions_

**Comment by vk496** [comment]
I proposed TravisCI because of the arm support. But Github Action + Docker BuildX is also ok. Thank you for the suggestion @neomilium :)
